server:
  port: 8013

spring:
  datasource:
    url: jdbc:mysql://192.168.0.103:3306/wxrobot?serverTimezone=GMT%2B8
    username: root
    password: DRsXT5ZJ6Oi55LPQ
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml  #对应mapper映射xml文件所在路径
  type-aliases-package: com.qsls9.catspringbootdemo.model  #对应实体类路径